version: '3.4'

services:
  modsenproject.identityserver:
    image: ${DOCKER_REGISTRY-}modsenprojectidentityserver
    build:
      context: .
      dockerfile: ModsenProject.IdentityServer/Dockerfile
