version: '3.4'

services:
  modsenproject.identityserver:
    container_name: indetity_server
    image: ${DOCKER_REGISTRY-}modsenprojectidentityserver
    environment:
      ASP_NET_IDENTITY_POSTGRES_CONNECTION_STRING: "Host=localhost;Port=5433;Database=aspnetidentity;Username=postgres;Password=root"
      IDENTITY_SERVER_DATABASE_CONNECTION_STRINGL: "Host=localhost;Port=5433;Database=aspnetidentity;Username=postgres;Password=root"
    build:
      context: .
      dockerfile: ModsenProject.IdentityServer/Dockerfile

  postgres.database:
    container_name: pg_database
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test_db"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
